 SELECT x."Season",
    x."Lg",
    x."Tm" AS "Team",
    x."Position",
    x."Value",
    y."Year",
    y."Player",
    y."Pos",
    y."Age",
    y."Tm",
    y."G",
    y."GS",
    y."MP",
    y."PER",
    y."TS_pct",
    y."3PAr",
    y."FTr",
    y."ORB_pct",
    y."DRB_pct",
    y."TRB_pct",
    y."AST_pct",
    y."STL_pct",
    y."BLK_pct",
    y."TOV_pct",
    y."USG_pct",
    y."OWS",
    y."DWS",
    y."WS",
    y."WS/48",
    y."OBPM",
    y."DBPM",
    y."BPM",
    y."VORP",
    y."FG",
    y."FGA",
    y."FG_pct",
    y."3P",
    y."3PA",
    y."3P_pct",
    y."2P",
    y."2PA",
    y."2P_pct",
    y."eFG_pct",
    y."FT",
    y."FTA",
    y."FT_pct",
    y."ORB",
    y."DRB",
    y."TRB",
    y."AST",
    y."STL",
    y."BLK",
    y."TOV",
    y."PF",
    y."PTS"
   FROM (allnba_unpivoted x
     LEFT JOIN seasons_stats y ON ((x."Value" = y."Player")))
  WHERE ("substring"(x."Season", 6, 2) = "substring"(y."Year", 3, 2))
  ORDER BY x."Season", x."Tm", x."Position";